'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.832
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Clase TopPage.
'''</summary>
'''<remarks>
'''Clase generada automáticamente.
'''</remarks>
Partial Public Class TopPage

    '''<summary>
    '''Control tblMenu.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tblMenu As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control txtNombre.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control CboMenu.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CboMenu As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Control cmdVolver.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmdVolver As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control cmdMisDatos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents cmdMisDatos As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Control CerrarSesion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificar, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CerrarSesion As Global.System.Web.UI.WebControls.LinkButton
End Class
